import React from 'react';
import { storiesOf } from '@storybook/react';
import { ThemeProvider } from "theme-ui";
const theme = require("../../theme.js");

import CtaBlock from 'gatsby-theme-octahedroid/src/components/cta-block';

storiesOf('Text block with call to action', module)
  .addDecorator(getStory => <ThemeProvider theme={theme}>{getStory()}</ThemeProvider>)
  .add('default', () => 
  <CtaBlock
    intro="Open-Source project"
    title="GatsbyJS Tailwind Starter"
    text="Octa - a simple landing page styled with tailwind and generated by GatsbyJS, Gatsby is a free and open source framework based on React that helps developers build blazing fast websites and apps."
    link="/"
    ctaText="Click here"
  />)
  .add('dark', () => 
  <CtaBlock
    intro="Open-Source project"
    title="GatsbyJS Tailwind Starter"
    text="Octa - a simple landing page styled with tailwind and generated by GatsbyJS, Gatsby is a free and open source framework based on React that helps developers build blazing fast websites and apps."
    link="/"
    ctaText="Click here"
    dark
  />)


